### ISSUE TITLE
Repetição de Caracteres

### ISSUE THREAD

**Issue by abarichello** [michelmilezzi/fallout2-ptbr#1]
https://github.com/michelmilezzi/fallout2-ptbr/blob/351fc3dda3f780588c9d493a81c73f58f2ed9b63/pt_br/game/MAP.MSG#L21
Seria intencional?

**Comment by michelmilezzi** [comment]
Definitivamente um bug. Identifiquei que aconteceu o mesmo com outras frases, provavelmente um problema com alguma expressão regular, não creio que seja da tradução do Google.

**Comment by abarichello** [comment]
Todos os arquivos que estão no repositório precisam ser traduzidos? Pretende fazer tudo pelo batch-translator mesmo?

**Comment by michelmilezzi** [comment]
Somente os da pasta "cuts" não foram traduzidos automaticamente. A ideia é disparar o batch-translator pra ganhar o máximo de tempo possível e depois somente revisar. Tens alguma sugestão? Qualquer contribuição é bem-vinda... :)

**Comment by abarichello** [comment]
Google tem como traduzir arquivos pelo browser, mas acho que seria tedioso adicionar os arquivos um por um.
[Aqui](https://translate.google.com/?tr=f&hl=en)

**Comment by michelmilezzi** [comment]
Existe um problema com o encoding original desses arquivos, são uma mistura de Windows-1252 com alguns caracteres especiais do Word (!). O Google translate trabalha em UTF-8, então eu escrevi o batch-translator pra tratar isso, preservando a característica deles (encoding, comentários, formatação, etc.).

**Comment by michelmilezzi** [comment]
Resolvido no PR #6
